name: Deploy Lambda with Serverless & ECR

on:
  push:
    branches:
      - main123

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

    - name: Build and push Docker image
      run: |
        ECR_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/my-lambda-image"
        docker build -t my-lambda-image .
        docker tag my-lambda-image:latest $ECR_URI:latest
        docker push $ECR_URI:latest

    - name: Install Serverless Framework
      run: npm install -g serverless

    - name: Deploy Lambda
      run: serverless deploy
